config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#show"
  # resources :sessions, only: [:new, :create, :destroy]
  # post "/sign_up", to: 'users#sign_up'
  # post '/login', to: 'users#login'
  # post '/authenticate', to: 'users#two_factor_auth'
  # post '/enable2fa', to: 'users#enable_2fa'
  # post '/update_password', to: 'users#update_password'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  get 'otp' => 'sessions#otp'
  post 'add_otp' => 'sessions#add_otp'
  get 'enable_2fa' => 'sessions#enable_2fa'
  get 'disable_2fa' => 'sessions#disable_2fa'
  get 'qr' => 'sessions#qr'
  post 'verify_otp' => 'sessions#verify_otp', as: :verify_otp
  get 'otp_authenticate' => 'sessions#otp_authenticate', as: :otp_authenticate
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
require 'securerandom'

class User < ApplicationRecord
  has_secure_password
  has_one_time_password

  #callback 
  after_create_commit :send_welcome_email
  before_update :send_otp_mail, if: -> { attribute_changed?(:otp) }
  
  #validation
  validates :email, presence: true, uniqueness: true

  def generate_otp
    SecureRandom.random_number(1000000).to_s.rjust(6, '0')
  end
  
  private

  def send_otp_mail
    ConfirmationMailer.send_otp(self).deliver_now
  end

  def send_welcome_email
    ConfirmationMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :set_current_session
  protected
  def require_auth
      unless current_user
          redirect_to root_path
      end
  end
  def verify_otp_status
      if session[:user_id].present? && !session[:otp_passed] && @user.otp_enabled
          redirect_to otp_path
      end
  end
  private
  def set_current_session
      @user = current_user
  end
  def current_user
      session[:user_id].present? ? User.find_by(id: session[:user_id]) : nil
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_auth, only: [:add_otp, :otp,:qr]
  before_action :verify_otp_status, only: [:add_otp]

  def new
  end

  def create
    @user = User.find_by(email: session_params[:email])
    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      session[:otp_passed] = false
      if !@user.verified || @user.otp_enabled
        @user.update(verified: true)
        session[:otp] = @user.generate_otp
        UserMailer.send_otp(@user.email, session[:otp]).deliver_now
        redirect_to otp_authenticate_path
      else
        redirect_to root_path
      end
    else
      flash[:error] = "Email or password is invalid!"
      redirect_to action: :new
    end
  end

  def otp
    otp_code = params[:otp_code]
    if @user.authenticate_otp(otp_code)
      session[:otp_passed] = true
      redirect_to root_path
    else
      flash[:error] = "Invalid OTP code"
      redirect_to otp_path
    end
  end

  def add_otp
    otp_code = params[:otp_code]
    if @user.authenticate_otp(otp_code, drift: 60)
      @user.update!(otp_enabled: true)
      redirect_to root_path
    else
      flash[:error] = "Invalid OTP code"
      redirect_to enable_2fa_path
    end
  end

  def enable_2fa
    @user = current_user
  end

  def disable_2fa
    @user = current_user
    @user.update(otp_enabled: false)
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    session[:otp_passed] = false
    redirect_to root_path
  end

  def verify_otp
    if session[:otp] == params[:otp]
      session[:otp_passed] = true
      redirect_to root_path
    else
      flash[:error] = "Invalid OTP. Please try again."
      redirect_to action: :otp_authenticate
    end
  end
  
  def otp_authenticate
  end

  def qr
    require "rqrcode"
    totp = ROTP::TOTP.new(@user.otp_secret_key, issuer: "OTP Test")
    qrcode = RQRCode::QRCode.new(totp.provisioning_uri(@user.email))
    send_data qrcode.as_png(size: 500), type: 'image/png', disposition: 'inline'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
require 'securerandom'
class UsersController < ApplicationController
  before_action :set_user, only: [:two_factor_auth, :enable_2fa, :update_password]

  def new
  end
  
  
  def create
    @user = User.new(user_params)
    if @user.save
      ConfirmationMailer.welcome_email(@user).deliver_now
      redirect_to login_path
    else
      flash[:error] = "Error- please try to create an account again."
      redirect_to new_user_path
    end
  end

  def show
  end
  
  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      token = JsonWebToken.encode(user: @user.id)
      unless @user.enable_2fa 
        otp = @user.generate_otp
        @user.update(otp: otp)
        render json: {token: token,message: 'Otp send successfully'}
      else
        render json: {token: token,message: 'You have logged in successfully'}
      end
    else
      render json: {error: 'Invalid Email or Password'}, status: :unprocessable_entity
    end
  end

  def two_factor_auth
    if @user.otp == params[:otp]
      render json: {message: 'You have successfully logged in'}
    else
      render json: {error: 'Otp is not valid'}, status: :unprocessable_entity
    end
  end

  def enable_2fa
    @user.update(enable_2fa: params[:enable_2fa])
    render json: {message: 'Your 2FA request updated successfully'}
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def set_user
    token = request.headers[:token]
    id = JsonWebToken.decode(token)
    @user = User.find_by(id: id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/json_web_token.rb
class JsonWebToken
  JWT_SECRET = Rails.application.secrets.secret_key_base

  def self.encode(payload, exp = 12.hours.from_now)
    payload[:exp] = exp.to_i
    JWT.encode(payload, JWT_SECRET)
  end

  def self.decode(token)
    body = JWT.decode(token, JWT_SECRET)[0].first.last
    return body
  end
end
  

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Two FA Authentication App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
 
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, url: users_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email %>
<br>
      <%= f.label :password %>
      <%= f.password_field :password %>
<br>
      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>
<br>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container text-center mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class="mb-4">Welcome to Your App</h1>

      <% if @user.nil? %>
        <div class="alert alert-info">
          <p>
            Please
            <%= link_to 'Log In', login_path %>
            <%= link_to 'Sign up', signup_path %>
          </p>
        </div>
      <% else %>
        <div class="card mt-4">
          <div class="card-body">
            <h2>Hello, <%= @user.email %>!</h2>

            <% if @user.otp_enabled %>
              <p>Your account is secured with OTP.</p>
              <br>
              <span class="badge badge-success">OTP Enabled</span>
              <br>
              <%= link_to 'Disable 2 factor authentication', disable_2fa_path, class: 'btn btn-primary' %>
            <% else %>
              <p>Your account is not yet secured with OTP.</p>
                <br>
                <%= link_to 'Enable 2 factor authentication', enable_2fa_path, class: 'btn btn-primary' %>
                <br>
            <% end %>

            <%= link_to 'Log Out', logout_path %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>